import "dotenv/config";
import OpenAI from 'openai'

const geminiClient = new OpenAI({
    apiKey: process.env.GEMINI_API_KEY,
    baseURL: "https://generativelanguage.googleapis.com/v1beta/openai/",
})

const groqClient = new OpenAI({
    apiKey: process.env.GROQ_API_KEY,
    baseURL: "https://api.groq.com/openai/v1",
})

const mistralClient = new OpenAI({
    apiKey: process.env.MISTRAL_API_KEY,
    baseURL: "https://api.mistral.ai/v1",
});

const openAIClient = new OpenAI({
    apiKey: process.env.OPENAI_API_KEY,
})

const COMPARE_SYSTEM_PROMPT = `
    You are an expert AI assistant. Only and only answer questions relate to the coding and engineering.

    Persona: You are a proficient AI Assistant.
    Persona Traits:
    - You always sound technical and use jargons.
    - You never answer back on personal things and you don't have a personal life.
    - All you know is how and what code is

    RULES:
    - Never use any markdown formatting.
    - Give response in plain text only.
    - Generate response in maximum 500 characters.
`

const SELF_CONSISTENT_SYSTEM_PROMPT = `
    You are a consensus-building, analytical AI.
    You will be provided with several different AI-generated responses to the same prompt.
    Your job is to analyze the reasoning in each, identify the consensus or majority-voted answer,
    and summarize the most accurate, fact-based conclusion from the group.
    The actual query of user will be there for reference as actual query.

    Each response was generated by an AI assistant using the same coding-focused instructions.
    
    Rules:
        - If multiple responses are equally accurate, you may mention more than one provider.
          Otherwise, identify the single best provider.
        - Never use markdown formatting even if any response is using it.
        - Always response in maximum of 500 characters.
        - Always mention the most accurate provider name.
        - Add an confidence score along with the most accurate response.
        - The response format should be json.
    
    Example Output Format:
        {
            "most_accurate_provider": "provider name",
            "confidence": 0.92,
            "response": "Your response",
        }
`



async function geminiResponse(prompt = "") {
    const result = await geminiClient.chat.completions.create({
        model: "gemini-3.1-flash-lite",
        messages: [
            {
                role: "system",
                content: COMPARE_SYSTEM_PROMPT,
            },
            {
                role: "user",
                content: prompt,
            }
        ]
    })

    return result.choices[0].message.content;
}

async function groqResponse(prompt = "") {
    const result = await groqClient.chat.completions.create({
        model: "llama-3.1-8b-instant",
        messages: [
            {
                role: "system",
                content: COMPARE_SYSTEM_PROMPT,
            },
            {
                role: "user",
                content: prompt,
            }
        ]
    })

    return result.choices[0].message.content;
}

async function mistralResponse(prompt = "") {
    const result = await mistralClient.chat.completions.create({
        model: "mistral-medium-2508",
        messages: [
            {
                role: "system",
                content: COMPARE_SYSTEM_PROMPT,
            },
            {
                role: "user",
                content: prompt,
            }
        ]
    })

    return result.choices[0].message.content;
}

async function openAIResponse(prompt = "", responses) {
    const result = await openAIClient.chat.completions.create({
        model: "gpt-5.4-mini",
        messages: [
            {
                role: "system",
                content: SELF_CONSISTENT_SYSTEM_PROMPT,
            },
            {
                role: "user",
                content: `
                Original Query:
                    ${prompt}
                
                Candidate Responses:
                    ${JSON.stringify(responses, null, 2)}
                `,
            },
        ],
        max_completion_tokens: 700,
        response_format: { type: "json_object" },
        temperature: 0,
    })

    return result.choices[0].message.content;
}

const query = "Why sky is blue?"

const results = await Promise.allSettled([
    geminiResponse(query),
    groqResponse(query),
    mistralResponse(query),
]);

console.log(results)
const providers = ['gemini', 'groq', 'mistral'];
const responses = results.
    map((r, i) => ({
        index: i,
        provider: providers[i],
        status: r.status,
        response: r.status === "fulfilled" ? r.value : null,
    }))
    .filter(r => r.status === "fulfilled");

if (responses.length === 0) {
    console.log("No provider returned a successful response.");

} else{

    const openAIRes = await openAIResponse(query, responses)
    console.log(JSON.parse(openAIRes));
}


